export const MATERIAL_CODEPOINTS: Record<string, string> = {
  // Navigation
  home: '\ue9b2',
  menu: '\ue5d2',
  arrow_back: '\ue5c4',
  arrow_back_ios: '\ue5e0',
  arrow_forward: '\ue5c8',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  expand_less: '\ue5ce',
  expand_more: '\ue5cf',
  close: '\ue5cd',
  more_vert: '\ue5d4',
  more_horiz: '\ue5d3',
  // Actions
  add: '\ue145',
  check: '\ue5ca',
  delete: '\ue92e',
  edit: '\uf097',
  search: '\ue8b6',
  share: '\ue80d',
  send: '\ue163',
  download: '\uf090',
  upload: '\uf09b',
  refresh: '\ue5d5',
  // Status / Info
  info: '\ue88e',
  warning: '\uf083',
  error: '\uf8b6',
  help: '\ue887',
  // Social / Profile
  person: '\uf0d3',
  people: '\uea21',
  favorite: '\ue87e',
  star: '\uf8d7',
  // Content
  settings: '\ue8b8',
  notifications: '\ue7f4',
  link: '\ue250',
  history: '\ue8b3',
  // Network / Connectivity
  wifi: '\ue63e',
  wifi_find: '\ueb31',
  bluetooth: '\ue1a7',
  // Misc
  lock: '\ue897',
  lock_open: '\ue898',
  visibility: '\ue8f4',
  visibility_off: '\ue8f5',
  calendar_today: '\ue935',
  schedule: '\ue8b5',
  location_on: '\ue0c8',
  phone: '\ue0cd',
  email: '\ue0be',
  camera: '\ue3af',
}
