export const MATERIAL_CODEPOINTS: Record<string, string> = {
  search: '\ue8b6',
  home: '\ue88a',
  menu: '\ue5d2',
  arrow_back: '\ue5c4',
  arrow_back_ios: '\ue5e0',
  add: '\ue145',
  close: '\ue5cd',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  more_vert: '\ue5d4',
  settings: '\ue8b8',
  person: '\ue7fd',
  favorite: '\ue87d',
  share: '\ue80d',
  delete: '\ue872',
  edit: '\ue3c9',
  check: '\ue5ca',
  info: '\ue88e',
  warning: '\ue002',
  error: '\ue000',
}
